name: vpn_prog
description: VPN
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"


dependencies:
  flag: ^7.0.0
  flutter:
    sdk: flutter
  get: ^4.6.5
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  firestore_ui: ^1.25.1
  cloud_firestore: ^4.8.4
  firebase_helpers: ^0.6.1
 

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true


  assets:
    - assets/vpn/
    - assets/images/img.png
    - assets/images/
    - assets/images/connected.png
    - assets/images/UP.png
    - assets/images/down.png
    - assets/images/encrypted.png
    